FROM nginx

LABEL maintainer="Lowrie@mr.shenhan@hotmail.com"
LABEL version="1.0.0"

WORKDIR /etc/nginx
ENV WEBDIR /usr/share/nginx/html

COPY /docs/.vuepress/dist/ ${WEBDIR}
COPY /default.conf ${WORKDIR}/conf.d/default.conf

EXPOSE 8081